apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: sonardb-secretstore
  namespace: sonarqube
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: sonarqube-sa
