apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jfrogdb-externalsecrets
  namespace: jfrog
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: jfrogdb-secretstore
    kind: SecretStore
  target:
    name: jfrogdb-secrets
  data:
  - secretKey: password
    remoteRef:
      key: jfrog-secret4
      property: password
  - secretKey: user
    remoteRef: 
      key: jfrog-secret4
      property: username
  - secretKey: url
    remoteRef:
      key: jfrog-secret4
      property: endpoint
